In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("PlayTennis.csv")
df

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [10]:
# Problem 1

# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak
# Play or No Play?

In [11]:
# Solution

# P(Yes | Sunny,Hot,High,Weak) = P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | Yes * P(Yes)

# P(No | Sunny,Hot,High,Weak) = P(Sunny | No) * P(Hot | No) * P(High | No) * P(Weak | No) * P(No)

# Compare and decide using the Maximum a posteriori rule

In [12]:
# Train
 # Look Up tablr
# Test

In [15]:
# 1. Find P(Y) and P(N)
df['play'].value_counts()

play
yes    9
no     5
Name: count, dtype: int64

In [16]:
prob_yes = 9/14
prob_no = 5/14

In [17]:
print(f"Probability of yes: {prob_yes}")
print(f"Probability of no: {prob_no}")

Probability of yes: 0.6428571428571429
Probability of no: 0.35714285714285715

In [18]:
# Outlook
pd.crosstab(df['outlook'],df['play'])

play      no  yes
outlook
overcast   0    4
rainy      2    3
sunny      3    2

In [21]:
prob_over_no = 0
prob_rainy_no = 2/5
prob_sunny_no = 3/5

prob_over_yes = 4/9
prob_rainy_yes = 3/9
prob_sunny_yes = 2/9

print(f"prob_over_no : {prob_over_no}")
print(f"prob_rainy_no : {prob_rainy_no}")
print(f"prob_sunny_no : {prob_sunny_no}")
print(f"prob_over_yes : {prob_over_yes}")
print(f"prob_rainy_yes : {prob_rainy_yes}")
print(f"prob_sunny_yes : {prob_sunny_yes}")

prob_over_no : 0
prob_rainy_no : 0.4
prob_sunny_no : 0.6
prob_over_yes : 0.4444444444444444
prob_rainy_yes : 0.3333333333333333
prob_sunny_yes : 0.2222222222222222

In [22]:
# Outlook
pd.crosstab(df['temp'],df['play'])

play  no  yes
temp
cool   1    3
hot    2    2
mild   2    4

In [23]:
prob_cool_no = 1/5  
prob_hot_no = 2/5
prob_mild_no = 2/5

prob_cool_yes = 3/9
prob_hot_yes = 2/9
prob_mild_yes = 4/9

print(f"Probability of cool given no: {prob_cool_no:.3f}")
print(f"Probability of hot given no: {prob_hot_no:.3f}")
print(f"Probability of mild given no: {prob_mild_no:.3f}")

print(f"Probability of cool given yes: {prob_cool_yes:.3f}")
print(f"Probability of hot given yes: {prob_hot_yes:.3f}")
print(f"Probability of mild given yes: {prob_mild_yes:.3f}")

Probability of cool given no: 0.200
Probability of hot given no: 0.400
Probability of mild given no: 0.400
Probability of cool given yes: 0.333
Probability of hot given yes: 0.222
Probability of mild given yes: 0.444

In [24]:
# humidity
pd.crosstab(df['humidity'],df['play'])

play      no  yes
humidity
high       4    3
normal     1    6

In [25]:
prob_high_no = 4/5
prob_normal_no = 1/5

prob_high_yes = 3/9
probl_normal_yes = 6/9

In [27]:
# wind
pd.crosstab(df['windy'],df['play'])

play   no  yes
windy
False   2    6
True    3    3

In [28]:
prob_false_no = 2/5
prob_true_no = 3/5

prob_false_yes  = 6/9
prob_true_yes = 3/9

In [30]:
# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak
# Play or No Play?

probability_yes = prob_yes * prob_sunny_yes * prob_hot_yes * prob_high_yes * prob_false_yes
print(probability_yes)

0.007054673721340388

In [31]:
probalbilty_not = prob_no * prob_sunny_no * prob_hot_no* prob_high_no *prob_false_no
print(probalbilty_not)

0.02742857142857143